[Settings]
ID = "netlify-generate-big-log-for-perf-devtools"


# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "/build-output/"
  # This will be your default build command
  command = "node index.js"
